name: budget_tracker
description: "A test project for FFG."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.3.3
  fl_chart: ^0.68.0
  get: ^4.6.6
  http: ^1.2.1
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

